import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:http/http.dart' as http;
import 'dart:convert';
import 'dart:async';
import 'dart:io';
import 'package:flutter_localizations/flutter_localizations.dart';
import 'package:shared_preferences/shared_preferences.dart';
import 'package:image_picker/image_picker.dart';

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  SharedPreferences prefs = await SharedPreferences.getInstance();
  int? savedId = prefs.getInt('userId');
  String? savedName = prefs.getString('username');

  runApp(MaterialApp(
    debugShowCheckedModeBanner: false,
    theme: ThemeData(primarySwatch: Colors.indigo, scaffoldBackgroundColor: const Color(0xFFE3F2FD), appBarTheme: const AppBarTheme(backgroundColor: Color(0xFF1565C0), foregroundColor: Colors.white), elevatedButtonTheme: ElevatedButtonThemeData(style: ElevatedButton.styleFrom(backgroundColor: const Color(0xFF1565C0), foregroundColor: Colors.white))),
    localizationsDelegates: [GlobalMaterialLocalizations.delegate, GlobalWidgetsLocalizations.delegate, GlobalCupertinoLocalizations.delegate],
    supportedLocales: [Locale('tr', 'TR')],
    locale: Locale('tr', 'TR'),
    home: (savedId != null && savedName != null) ? UsersPage(myId: savedId, myName: savedName) : const LoginPage(),
  ));
}

const String baseUrl = "http://localhost:5152/api"; 

Widget buildProfileImage(String? data, bool isGroup, double radius) {
  if (data == null || data == "person" || data == "group" || data.isEmpty) {
    return CircleAvatar(radius: radius, backgroundColor: isGroup ? Colors.orange : Colors.indigo, child: Icon(isGroup ? Icons.group : Icons.person, size: radius, color: Colors.white));
  } else {
    try { return CircleAvatar(radius: radius, backgroundImage: MemoryImage(base64Decode(data))); } catch (e) { return CircleAvatar(radius: radius, child: const Icon(Icons.error)); }
  }
}

// ... GİRİŞ, PROFİL, GRUP SAYFALARI AYNI (Kısaltıldı) ...
// (Tam kod aşağıda)

class LoginPage extends StatefulWidget { const LoginPage({super.key}); @override State<LoginPage> createState() => _LoginPageState(); }
class _LoginPageState extends State<LoginPage> {
  final TextEditingController _u = TextEditingController(); final TextEditingController _p = TextEditingController();
  Future<void> login() async { if (_u.text.isEmpty || _p.text.isEmpty) return; try { final res = await http.post(Uri.parse("$baseUrl/Users/login"), headers: {"Content-Type": "application/json"}, body: json.encode({"username": _u.text, "password": _p.text})); if (res.statusCode == 200) { final d = json.decode(res.body); SharedPreferences prefs = await SharedPreferences.getInstance(); await prefs.setInt('userId', d['id']); await prefs.setString('username', d['username']); Navigator.pushReplacement(context, MaterialPageRoute(builder: (c) => UsersPage(myId: d['id'], myName: d['username']))); } else { ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content: Text("Hatalı Giriş!"))); } } catch (e) { print(e); } }
  @override Widget build(BuildContext context) { return Scaffold(backgroundColor: Colors.white, body: Center(child: Padding(padding: const EdgeInsets.all(30), child: Column(mainAxisAlignment: MainAxisAlignment.center, children: [const Icon(Icons.lock, size: 80, color: Colors.indigo), const SizedBox(height: 10), const Text("SecureChat", style: TextStyle(fontSize: 24, fontWeight: FontWeight.bold, color: Colors.indigo)), const SizedBox(height: 30), TextField(controller: _u, decoration: const InputDecoration(border: OutlineInputBorder(), labelText: 'Kullanıcı Adı', prefixIcon: Icon(Icons.person))), const SizedBox(height: 15), TextField(controller: _p, obscureText: true, onSubmitted: (v)=>login(), decoration: const InputDecoration(border: OutlineInputBorder(), labelText: 'Parola', prefixIcon: Icon(Icons.lock))), const SizedBox(height: 20), ElevatedButton(onPressed: login, style: ElevatedButton.styleFrom(minimumSize: const Size(double.infinity, 50)), child: const Text("Giriş Yap"))])))); }
}

class ProfilePage extends StatefulWidget { final int myId; const ProfilePage({super.key, required this.myId}); @override State<ProfilePage> createState() => _ProfilePageState(); }
class _ProfilePageState extends State<ProfilePage> { TextEditingController nickCtrl = TextEditingController(); TextEditingController aboutCtrl = TextEditingController(); String? currentIcon; bool loading = true; @override void initState() { super.initState(); loadProfile(); } Future<void> loadProfile() async { try { final res = await http.get(Uri.parse("$baseUrl/Users/profile/${widget.myId}")); if (res.statusCode == 200) { var data = json.decode(res.body); setState(() { nickCtrl.text = data['nickName'] ?? ""; aboutCtrl.text = data['about'] ?? ""; currentIcon = data['profileIcon']; loading = false; }); } } catch (e) { print(e); } } Future<void> pickImage() async { final ImagePicker picker = ImagePicker(); final XFile? image = await picker.pickImage(source: ImageSource.gallery, maxWidth: 400); if (image != null) { List<int> imageBytes = await image.readAsBytes(); setState(() { currentIcon = base64Encode(imageBytes); }); } } Future<void> saveProfile() async { var body = { "nickName": nickCtrl.text, "about": aboutCtrl.text, "profileIcon": currentIcon ?? "person" }; await http.put(Uri.parse("$baseUrl/Users/profile/${widget.myId}"), headers: {"Content-Type":"application/json"}, body: json.encode(body)); ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content: Text("Profil Güncellendi!"))); Navigator.pop(context); } @override Widget build(BuildContext context) { return Scaffold(appBar: AppBar(title: const Text("Profilim")), body: loading ? const Center(child: CircularProgressIndicator()) : SingleChildScrollView(padding: const EdgeInsets.all(20), child: Column(children: [GestureDetector(onTap: pickImage, child: Stack(alignment: Alignment.bottomRight, children: [buildProfileImage(currentIcon, false, 60), const CircleAvatar(backgroundColor: Colors.white, radius: 18, child: Icon(Icons.camera_alt, size: 20, color: Colors.indigo))])), const SizedBox(height: 20), TextField(controller: nickCtrl, decoration: const InputDecoration(labelText: "Görünen İsim (@Nick)", border: OutlineInputBorder(), prefixIcon: Icon(Icons.alternate_email))), const SizedBox(height: 20), TextField(controller: aboutCtrl, decoration: const InputDecoration(labelText: "Hakkımda", border: OutlineInputBorder(), prefixIcon: Icon(Icons.info_outline))), const SizedBox(height: 20), SizedBox(width: double.infinity, child: ElevatedButton(onPressed: saveProfile, child: const Text("KAYDET")))]))); }
}

class OtherUserProfilePage extends StatefulWidget { final int userId; const OtherUserProfilePage({super.key, required this.userId}); @override State<OtherUserProfilePage> createState() => _OtherUserProfilePageState(); }
class _OtherUserProfilePageState extends State<OtherUserProfilePage> { dynamic userData; bool loading = true; @override void initState() { super.initState(); loadProfile(); } Future<void> loadProfile() async { try { final res = await http.get(Uri.parse("$baseUrl/Users/profile/${widget.userId}")); if (res.statusCode == 200) { setState(() { userData = json.decode(res.body); loading = false; }); } } catch (e) { print(e); } } @override Widget build(BuildContext context) { return Scaffold(appBar: AppBar(title: const Text("Kullanıcı Bilgisi")), body: loading ? const Center(child: CircularProgressIndicator()) : Center(child: Column(mainAxisAlignment: MainAxisAlignment.center, children: [buildProfileImage(userData['profileIcon'], false, 80), const SizedBox(height: 20), Text(userData['username'], style: const TextStyle(fontSize: 24, fontWeight: FontWeight.bold)), Text(userData['nickName'] ?? "", style: const TextStyle(fontSize: 18, color: Colors.grey)), const SizedBox(height: 20), Padding(padding: const EdgeInsets.symmetric(horizontal: 30), child: Container(padding: const EdgeInsets.all(20), decoration: BoxDecoration(color: Colors.white, borderRadius: BorderRadius.circular(10)), child: Text(userData['about'] ?? "Hakkında bilgisi yok.", textAlign: TextAlign.center, style: const TextStyle(fontSize: 16)))),]))); }
}

class CreateGroupPage extends StatefulWidget { final int myId; const CreateGroupPage({super.key, required this.myId}); @override State<CreateGroupPage> createState() => _CreateGroupPageState(); }
class _CreateGroupPageState extends State<CreateGroupPage> { TextEditingController nameCtrl = TextEditingController(); List<dynamic> allUsers = []; List<int> selectedUserIds = []; String? groupIcon; @override void initState() { super.initState(); loadUsers(); } Future<void> loadUsers() async { final res = await http.get(Uri.parse("$baseUrl/Users/${widget.myId}")); if(res.statusCode == 200) { var data = json.decode(res.body); setState(() { allUsers = (data as List).where((u) => u['isGroup'] == false).toList(); }); } } Future<void> pickImage() async { final ImagePicker picker = ImagePicker(); final XFile? image = await picker.pickImage(source: ImageSource.gallery, maxWidth: 400); if (image != null) { List<int> imageBytes = await image.readAsBytes(); setState(() { groupIcon = base64Encode(imageBytes); }); } } Future<void> createGroup() async { if(nameCtrl.text.isEmpty) return; var body = { "groupName": nameCtrl.text, "creatorId": widget.myId, "memberIds": selectedUserIds, "groupIcon": groupIcon ?? "group" }; final res = await http.post(Uri.parse("$baseUrl/Groups/create"), headers: {"Content-Type":"application/json"}, body: json.encode(body)); if(res.statusCode == 200) { Navigator.pop(context); ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content: Text("Grup Kuruldu!"))); } } @override Widget build(BuildContext context) { return Scaffold(appBar: AppBar(title: const Text("Yeni Grup Kur")), body: Column(children: [Padding(padding: const EdgeInsets.all(16), child: Row(children: [GestureDetector(onTap: pickImage, child: buildProfileImage(groupIcon, true, 30)), const SizedBox(width: 15), Expanded(child: TextField(controller: nameCtrl, decoration: const InputDecoration(labelText: "Grup Adı", border: OutlineInputBorder())))] )), const Padding(padding: EdgeInsets.only(left:16), child: Align(alignment: Alignment.centerLeft, child: Text("Katılımcı Seç:", style: TextStyle(fontWeight: FontWeight.bold)))), Expanded(child: ListView.builder(itemCount: allUsers.length, itemBuilder: (c, i) { var u = allUsers[i]; bool isSel = selectedUserIds.contains(u['id']); return CheckboxListTile(value: isSel, title: Text(u['name']), secondary: buildProfileImage(u['profileIcon'], false, 20), onChanged: (v) { setState(() { if(v!) selectedUserIds.add(u['id']); else selectedUserIds.remove(u['id']); }); }); })), Padding(padding: const EdgeInsets.all(16), child: SizedBox(width: double.infinity, child: ElevatedButton(onPressed: createGroup, child: const Text("GRUBU OLUŞTUR"))))])); }
}

class GroupInfoPage extends StatefulWidget { final int groupId; const GroupInfoPage({super.key, required this.groupId}); @override State<GroupInfoPage> createState() => _GroupInfoPageState(); }
class _GroupInfoPageState extends State<GroupInfoPage> { TextEditingController nameCtrl = TextEditingController(); TextEditingController descCtrl = TextEditingController(); String? groupIcon; bool loading = true; @override void initState() { super.initState(); loadGroup(); } Future<void> loadGroup() async { final res = await http.get(Uri.parse("$baseUrl/Groups/${widget.groupId}")); if(res.statusCode == 200) { var d = json.decode(res.body); setState(() { nameCtrl.text = d['groupName']; descCtrl.text = d['description'] ?? ""; groupIcon = d['groupIcon']; loading = false; }); } } Future<void> pickImage() async { final ImagePicker picker = ImagePicker(); final XFile? image = await picker.pickImage(source: ImageSource.gallery, maxWidth: 400); if (image != null) { List<int> imageBytes = await image.readAsBytes(); setState(() { groupIcon = base64Encode(imageBytes); }); } } Future<void> saveGroup() async { var body = { "groupName": nameCtrl.text, "description": descCtrl.text, "groupIcon": groupIcon ?? "group" }; await http.put(Uri.parse("$baseUrl/Groups/${widget.groupId}"), headers: {"Content-Type":"application/json"}, body: json.encode(body)); ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content: Text("Grup Güncellendi!"))); Navigator.pop(context, true); } @override Widget build(BuildContext context) { return Scaffold(appBar: AppBar(title: const Text("Grup Ayarları")), body: loading ? const Center(child: CircularProgressIndicator()) : SingleChildScrollView(padding: const EdgeInsets.all(20), child: Column(children: [GestureDetector(onTap: pickImage, child: Stack(alignment: Alignment.bottomRight, children: [buildProfileImage(groupIcon, true, 60), const CircleAvatar(backgroundColor: Colors.white, radius: 18, child: Icon(Icons.edit, size: 20, color: Colors.indigo))])), const SizedBox(height: 20), TextField(controller: nameCtrl, decoration: const InputDecoration(labelText: "Grup Adı", border: OutlineInputBorder())), const SizedBox(height: 20), TextField(controller: descCtrl, decoration: const InputDecoration(labelText: "Grup Açıklaması", border: OutlineInputBorder())), const SizedBox(height: 20), SizedBox(width: double.infinity, child: ElevatedButton(onPressed: saveGroup, child: const Text("DEĞİŞİKLİKLERİ KAYDET")))]))); }
}

class StarredMessagesPage extends StatefulWidget { final int myId; const StarredMessagesPage({super.key, required this.myId}); @override State<StarredMessagesPage> createState() => _StarredMessagesPageState(); }
class _StarredMessagesPageState extends State<StarredMessagesPage> {
  List<dynamic> messages = []; bool isLoading = true; bool isSelectionMode = false; List<int> selectedIds = [];
  @override void initState() { super.initState(); fetchStarred(); }
  Future<void> fetchStarred() async { try { final res = await http.get(Uri.parse("$baseUrl/Messages/starred/${widget.myId}")); if (res.statusCode == 200) setState(() { messages = json.decode(res.body); isLoading = false; }); } catch (e) { print(e); } }
  Future<void> unstarSelected() async { for(int id in selectedIds) { await http.put(Uri.parse("$baseUrl/Messages/star/$id")); } setState(() { isSelectionMode = false; selectedIds.clear(); }); fetchStarred(); ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content: Text("Yıldızlar kaldırıldı."))); }
  void showMsgMenu(dynamic msg) { bool isGroup = msg['groupId'] != null; int targetId = isGroup ? msg['groupId'] : ((msg['senderId'] == widget.myId) ? msg['receiverId'] : msg['senderId']); String targetName = isGroup ? (msg['groupName'] ?? "Grup") : msg['senderName']; showModalBottomSheet(context: context, builder: (ctx) => Wrap(children: [ListTile(leading: const Icon(Icons.chat), title: const Text("Sohbete Git"), onTap: (){ Navigator.pop(ctx); Navigator.push(context, MaterialPageRoute(builder: (c) => ChatPage(myId: widget.myId, targetId: targetId, targetName: targetName, isGroup: isGroup, highlightMessageId: msg['id']))); }), ListTile(leading: const Icon(Icons.star_border), title: const Text("Yıldızı Kaldır"), onTap: () async { Navigator.pop(ctx); await http.put(Uri.parse("$baseUrl/Messages/star/${msg['id']}")); fetchStarred(); }), ListTile(leading: const Icon(Icons.check_box_outlined), title: const Text("Seç"), onTap: (){ Navigator.pop(ctx); setState(() { isSelectionMode = true; selectedIds.add(msg['id']); }); }),])); }
  String decrypt(String e) { try { return utf8.decode(base64Decode(e)); } catch (x) { return "???"; } }
  @override Widget build(BuildContext context) { Map<String, List<dynamic>> grouped = {}; for (var m in messages) { String tag = m['starTag'] ?? "Genel"; if (!grouped.containsKey(tag)) grouped[tag] = []; grouped[tag]!.add(m); } return WillPopScope(onWillPop: () async { if (isSelectionMode) { setState(() { isSelectionMode = false; selectedIds.clear(); }); return false; } return true; }, child: Scaffold(appBar: AppBar(title: Text(isSelectionMode ? "${selectedIds.length} Seçildi" : "Yıldızlı Mesajlar"), leading: isSelectionMode ? IconButton(icon: const Icon(Icons.close), onPressed: (){ setState(() { isSelectionMode = false; selectedIds.clear(); }); }) : const BackButton(),), body: isLoading ? const Center(child: CircularProgressIndicator()) : ListView(children: grouped.entries.map((entry) { return ExpansionTile(title: Text(entry.key, style: const TextStyle(fontWeight: FontWeight.bold, color: Color(0xFF1565C0))), initiallyExpanded: true, children: entry.value.map((m) { final bool isSelected = selectedIds.contains(m['id']); bool isGroupMsg = m['groupId'] != null; return ListTile(leading: isSelectionMode ? Checkbox(value: isSelected, onChanged: (v) { setState(() { if(v!) selectedIds.add(m['id']); else selectedIds.remove(m['id']); if(selectedIds.isEmpty) isSelectionMode = false; }); }) : const Icon(Icons.star, color: Colors.orange), title: Row(children: [Text(m['senderName'], style: const TextStyle(fontWeight: FontWeight.bold)), if(isGroupMsg) ...[const SizedBox(width:5), Container(padding:const EdgeInsets.symmetric(horizontal:4,vertical:2), decoration:BoxDecoration(color:Colors.orange[100], borderRadius:BorderRadius.circular(4)), child:Text(m['groupName']??"Grup", style:const TextStyle(fontSize:10, color:Colors.deepOrange)))]]), subtitle: Text(decrypt(m['encryptedContent']), maxLines: 2, overflow: TextOverflow.ellipsis), tileColor: isSelected ? Colors.green[100] : null, onTap: () { if(isSelectionMode) { setState(() { if(isSelected) selectedIds.remove(m['id']); else selectedIds.add(m['id']); }); } else { showMsgMenu(m); } },); }).toList(),); }).toList(),), bottomNavigationBar: isSelectionMode ? BottomAppBar(child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [TextButton.icon(icon: const Icon(Icons.star_border, color: Colors.red), label: const Text("Seçilenleri Kaldır", style:TextStyle(color:Colors.red)), onPressed: unstarSelected),])) : null,),); }
}

// ================= KİŞİ LİSTESİ =================
class UsersPage extends StatefulWidget { final int myId; final String myName; const UsersPage({super.key, required this.myId, required this.myName}); @override State<UsersPage> createState() => _UsersPageState(); }
class _UsersPageState extends State<UsersPage> {
  List<dynamic> users = []; Timer? timer;
  @override void initState() { super.initState(); fetchUsers(); timer = Timer.periodic(const Duration(seconds: 2), (t) => fetchUsers()); }
  @override void dispose() { timer?.cancel(); super.dispose(); }
  Future<void> fetchUsers() async { try { final res = await http.get(Uri.parse("$baseUrl/Users/${widget.myId}")); if (res.statusCode == 200 && mounted) setState(() { users = json.decode(res.body); }); } catch (e) { print(e); } }
  Future<void> addUserToList(int otherId) async { String enc = base64Encode(utf8.encode("👋")); await http.post(Uri.parse("$baseUrl/Messages"), headers: {"Content-Type":"application/json"}, body: json.encode({"senderId":widget.myId, "receiverId":otherId, "encryptedContent":enc})); fetchUsers(); ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content: Text("Eklendi!"))); }
  Future<void> logout() async { SharedPreferences prefs = await SharedPreferences.getInstance(); await prefs.clear(); Navigator.pushReplacement(context, MaterialPageRoute(builder: (c)=>const LoginPage())); }
  void showSearchDialog() { TextEditingController c = TextEditingController(); showDialog(context: context, builder: (ctx) => AlertDialog(title: const Text("Kullanıcı Ara"), content: TextField(controller: c, decoration: const InputDecoration(hintText: "Kullanıcı Adı", prefixIcon: Icon(Icons.search))), actions: [TextButton(onPressed: ()=>Navigator.pop(ctx), child: const Text("İptal")), ElevatedButton(style: ElevatedButton.styleFrom(backgroundColor: const Color(0xFF075E54), foregroundColor: Colors.white), onPressed: () async { if(c.text.isEmpty) return; try { final res = await http.get(Uri.parse("$baseUrl/Users/search/${c.text}")); if (!ctx.mounted) return; if(res.statusCode==200) { Navigator.pop(ctx); showFoundUserDialog(json.decode(res.body)); } else { Navigator.pop(ctx); ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content: Text("Kullanıcı bulunamadı!"))); } } catch(e) { print(e); } }, child: const Text("ARA"))])); }
  void showFoundUserDialog(dynamic user) { if(user['id'] == widget.myId) { ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content: Text("Kendinizi ekleyemezsiniz."))); return; } showDialog(context: context, builder: (ctx) => AlertDialog(content: Column(mainAxisSize: MainAxisSize.min, children: [buildProfileImage(user['profileIcon'], false, 30), const SizedBox(height:10), Text(user['username'], style:const TextStyle(fontSize:20, fontWeight:FontWeight.bold))]), actions: [TextButton(onPressed: (){ Navigator.pop(ctx); addUserToList(user['id']); }, child: const Text("Listeye Ekle")), ElevatedButton(onPressed: (){ Navigator.pop(ctx); Navigator.push(context, MaterialPageRoute(builder: (c)=>ChatPage(myId: widget.myId, targetId: user['id'], targetName: user['username'], isGroup: false))).then((_)=>fetchUsers()); }, child: const Text("Mesaj Yaz"))])); }
  String decrypt(String e) { if(e.startsWith("🚫")) return e; if(e.isEmpty) return ""; try { return utf8.decode(base64Decode(e)); } catch(x) { return "🔒"; } }
  String fmtTime(String? d) { if(d==null)return""; try{ var t=DateTime.parse(d).toLocal(); return "${t.hour.toString().padLeft(2,'0')}:${t.minute.toString().padLeft(2,'0')}"; }catch(e){return"";} }
  Widget buildTick(bool? d, bool? r) { bool rd=r??false; bool dl=d??false; if(rd) return const Icon(Icons.done_all, size:14, color:Colors.blue); if(dl) return const Icon(Icons.done_all, size:14, color:Colors.grey); return const Icon(Icons.check, size:14, color:Colors.grey); }
  
  @override Widget build(BuildContext context) { return Scaffold(appBar: AppBar(title: const Text("Sohbetler"), actions: [IconButton(icon: const Icon(Icons.star), onPressed: () => Navigator.push(context, MaterialPageRoute(builder: (c)=>StarredMessagesPage(myId: widget.myId)))), IconButton(icon: const Icon(Icons.person), onPressed: () => Navigator.push(context, MaterialPageRoute(builder: (c)=>ProfilePage(myId: widget.myId))).then((_)=>fetchUsers())), IconButton(icon: const Icon(Icons.search), onPressed: showSearchDialog), IconButton(icon: const Icon(Icons.exit_to_app), onPressed: logout)]), floatingActionButton: FloatingActionButton(onPressed: () => Navigator.push(context, MaterialPageRoute(builder: (c)=>CreateGroupPage(myId: widget.myId))).then((_) => fetchUsers()), child: const Icon(Icons.group_add), tooltip: "Yeni Grup"), body: users.isEmpty ? const Center(child: Text("Sohbet yok.")) : ListView.builder(itemCount: users.length, itemBuilder: (c, i) { final u = users[i]; bool isGrp = u['isGroup'] ?? false; return Column(children: [ListTile(leading: buildProfileImage(u['profileIcon'], isGrp, 24), title: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Text(u['name'], style:const TextStyle(fontWeight: FontWeight.bold)), Text(fmtTime(u['lastMessageTime']), style: const TextStyle(fontSize:12, color: Colors.grey))]), subtitle: Row(children: [if(u['lastMessageSenderId']==widget.myId && !isGrp) ...[buildTick(u['lastMessageIsDelivered'], u['lastMessageIsRead']), const SizedBox(width:5)], Expanded(child: Text(decrypt(u['lastMessage']), maxLines:1, overflow:TextOverflow.ellipsis))]), 
  // BALONCUK BURADA
  trailing: u['unreadCount'] > 0 ? CircleAvatar(radius: 12, backgroundColor: const Color(0xFF00BFA5), child: Text("${u['unreadCount']}", style: const TextStyle(color: Colors.white, fontSize: 12, fontWeight: FontWeight.bold))) : null, 
  onTap: () => Navigator.push(context, MaterialPageRoute(builder: (c)=>ChatPage(myId: widget.myId, targetId: u['id'], targetName: u['name'], isGroup: isGrp))).then((_)=>fetchUsers())), const Divider(height:1)]); })); }
}

// ================= SOHBET EKRANI =================
class ChatPage extends StatefulWidget { final int myId; final int targetId; final String targetName; final bool isGroup; final int? highlightMessageId; const ChatPage({super.key, required this.myId, required this.targetId, required this.targetName, required this.isGroup, this.highlightMessageId}); @override State<ChatPage> createState() => _ChatPageState(); }
class _ChatPageState extends State<ChatPage> {
  final TextEditingController _msgCtrl = TextEditingController(); final ScrollController _scrollCtrl = ScrollController(); List<dynamic> messages = []; Timer? timer; String? replyingTo; int _lastMsgCount = 0; int? _flashingId;
  @override void initState() { super.initState(); _flashingId = widget.highlightMessageId; fetchMessages(); timer = Timer.periodic(const Duration(seconds: 1), (t) => fetchMessages()); if (_flashingId != null) { Future.delayed(const Duration(seconds: 1), () { if(mounted) setState(() { _flashingId = null; }); }); } }
  @override void dispose() { timer?.cancel(); _scrollCtrl.dispose(); super.dispose(); }
  void _scrollToBottom() { if (_scrollCtrl.hasClients) _scrollCtrl.animateTo(_scrollCtrl.position.maxScrollExtent, duration: const Duration(milliseconds: 300), curve: Curves.easeOut); }
  Future<void> fetchMessages() async { try { final res = await http.get(Uri.parse("$baseUrl/Messages/conversation?myId=${widget.myId}&targetId=${widget.targetId}&isGroup=${widget.isGroup}")); if (res.statusCode == 200 && mounted) { var newMsgs = json.decode(res.body); setState(() { messages = newMsgs; }); if (widget.highlightMessageId == null && messages.length > _lastMsgCount) { _lastMsgCount = messages.length; WidgetsBinding.instance.addPostFrameCallback((_) => _scrollToBottom()); } } } catch (e) { print(e); } }
  Future<void> sendMessage({DateTime? scheduledTime}) async { if (_msgCtrl.text.isEmpty) return; String textToSend = _msgCtrl.text; if(replyingTo != null) { textToSend = ">> ${replyingTo!.length > 15 ? replyingTo!.substring(0,15)+'...' : replyingTo}\n$textToSend"; setState(() { replyingTo = null; }); } String enc = base64Encode(utf8.encode(textToSend)); Map<String, dynamic> body = {"senderId": widget.myId, "encryptedContent": enc}; if (widget.isGroup) body["groupId"] = widget.targetId; else body["receiverId"] = widget.targetId; if (scheduledTime != null) body["scheduledTime"] = scheduledTime.toIso8601String(); await http.post(Uri.parse("$baseUrl/Messages"), headers: {"Content-Type":"application/json"}, body: json.encode(body)); _msgCtrl.clear(); await fetchMessages(); WidgetsBinding.instance.addPostFrameCallback((_) => _scrollToBottom()); if(scheduledTime!=null) ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content: Text("Zamanlandı!"))); }
  void showScheduleMenu() { showModalBottomSheet(context: context, builder: (ctx) => Wrap(children: [ListTile(leading: const Icon(Icons.timer_10), title: const Text("15 Dk Sonra"), onTap: (){ Navigator.pop(ctx); sendMessage(scheduledTime: DateTime.now().add(const Duration(minutes: 15))); }), ListTile(leading: const Icon(Icons.timer), title: const Text("1 Saat Sonra"), onTap: (){ Navigator.pop(ctx); sendMessage(scheduledTime: DateTime.now().add(const Duration(hours: 1))); }), ListTile(leading: const Icon(Icons.calendar_today), title: const Text("1 Gün Sonra"), onTap: (){ Navigator.pop(ctx); sendMessage(scheduledTime: DateTime.now().add(const Duration(days: 1))); }), ListTile(leading: const Icon(Icons.edit_calendar), title: const Text("Tarih Seç..."), onTap: () async { Navigator.pop(ctx); DateTime? d = await showDatePicker(context: context, initialDate: DateTime.now(), firstDate: DateTime.now(), lastDate: DateTime(2030), locale: const Locale('tr','TR'), confirmText: "SEÇ", cancelText: "İPTAL"); if(d!=null) { TimeOfDay? t = await showTimePicker(context: context, initialTime: TimeOfDay.now(), builder: (c,child)=>Localizations.override(context:c, locale:const Locale('tr','TR'), child: MediaQuery(data:MediaQuery.of(c).copyWith(alwaysUse24HourFormat:true), child: child!))); if(t!=null) sendMessage(scheduledTime: DateTime(d.year,d.month,d.day,t.hour,t.minute)); } })])); }
  Future<void> deleteMessage(int id, String mode) async { await http.delete(Uri.parse("$baseUrl/Messages/$id?requestUserId=${widget.myId}&mode=$mode")); fetchMessages(); }
  Future<void> starMessage(int id, String? tag) async { await http.put(Uri.parse("$baseUrl/Messages/star/$id?tag=${tag ?? ''}")); fetchMessages(); }
  Future<void> pinMessage(int id) async { await http.put(Uri.parse("$baseUrl/Messages/pin/$id")); fetchMessages(); }
  void showStarDialog(int msgId) { showDialog(context: context, builder: (ctx) { TextEditingController customTagCtrl = TextEditingController(); return AlertDialog(title: const Text("Kategori Seç"), content: Column(mainAxisSize: MainAxisSize.min, children: [ListTile(leading: const Icon(Icons.star, color: Colors.orange), title: const Text("Genel"), onTap: () { Navigator.pop(ctx); starMessage(msgId, "Genel"); }), ListTile(leading: const Icon(Icons.school, color: Colors.blue), title: const Text("Ödev"), onTap: () { Navigator.pop(ctx); starMessage(msgId, "Ödev"); }), ListTile(leading: const Icon(Icons.work, color: Colors.red), title: const Text("Önemli"), onTap: () { Navigator.pop(ctx); starMessage(msgId, "Önemli"); }), const Divider(), TextField(controller: customTagCtrl, decoration: const InputDecoration(hintText: "Yeni Kategori...", suffixIcon: Icon(Icons.add))), const SizedBox(height: 10), ElevatedButton(onPressed: () { if(customTagCtrl.text.isNotEmpty) { Navigator.pop(ctx); starMessage(msgId, customTagCtrl.text); } }, child: const Text("Ekle"))])); }); }
  void showMessageMenu(Offset position, dynamic msg, bool isMe) async { String decodedContent = decrypt(msg['encryptedContent'], false); final selected = await showMenu(context: context, position: RelativeRect.fromLTRB(position.dx, position.dy, position.dx + 1, position.dy + 1), items: [const PopupMenuItem(value: 'reply', child: Row(children: [Icon(Icons.reply), SizedBox(width:8), Text("Cevapla")])), const PopupMenuItem(value: 'copy', child: Row(children: [Icon(Icons.copy), SizedBox(width:8), Text("Kopyala")])), const PopupMenuItem(value: 'star', child: Row(children: [Icon(Icons.star), SizedBox(width:8), Text("Yıldız Ekle")])), const PopupMenuItem(value: 'pin', child: Row(children: [Icon(Icons.push_pin), SizedBox(width:8), Text("Sabitle")])), const PopupMenuItem(value: 'delete', child: Row(children: [Icon(Icons.delete, color:Colors.red), SizedBox(width:8), Text("Sil", style:TextStyle(color:Colors.red))]))]); if (selected == null) return; if (selected == 'delete') { if (!mounted) return; final delOpt = await showMenu(context: context, position: RelativeRect.fromLTRB(position.dx, position.dy, position.dx+1, position.dy+1), items: [const PopupMenuItem(value: 'me', child: Text("Benden Sil")), if (isMe) const PopupMenuItem(value: 'everyone', child: Text("Herkesten Sil", style: TextStyle(color: Colors.red))), const PopupMenuItem(value: 'cancel', child: Text("Geri"))]); if (delOpt != null && delOpt != 'cancel') deleteMessage(msg['id'], delOpt); } else if (selected == 'star') { showStarDialog(msg['id']); } else if (selected == 'copy') { Clipboard.setData(ClipboardData(text: decodedContent)); ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content: Text("Kopyalandı"))); } else if (selected == 'reply') { setState(() { replyingTo = decodedContent; }); } else if (selected == 'pin') { pinMessage(msg['id']); } }
  String decrypt(String e, bool del) { if(del) return "🚫 Bu mesaj silindi"; try { return utf8.decode(base64Decode(e)); } catch(x) { return "???"; } }
  String fmtTime(String? d) { if(d==null) return ""; try{ var t=DateTime.parse(d).toLocal(); return "${t.hour.toString().padLeft(2,'0')}:${t.minute.toString().padLeft(2,'0')}"; }catch(e){return"";} }
  Widget buildTick(bool? d, bool? r) { bool rd=r??false; bool dl=d??false; if(rd) return const Icon(Icons.done_all, size:16, color:Colors.blue); if(dl) return const Icon(Icons.done_all, size:16, color:Colors.grey); return const Icon(Icons.check, size:16, color:Colors.grey); }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: GestureDetector(
          onTap: () async {
            if(widget.isGroup) { bool? updated = await Navigator.push(context, MaterialPageRoute(builder: (c) => GroupInfoPage(groupId: widget.targetId))); if(updated == true) setState(() {}); }
            else { Navigator.push(context, MaterialPageRoute(builder: (c) => OtherUserProfilePage(userId: widget.targetId))); }
          },
          child: Row(children: [buildProfileImage(null, widget.isGroup, 16), const SizedBox(width:10), Text(widget.targetName)]),
        ), 
        backgroundColor: const Color(0xFF1565C0), foregroundColor: Colors.white
      ),
      body: Column(children: [
        Expanded(child: ListView.builder(controller: _scrollCtrl, itemCount: messages.length, itemBuilder: (c, i) {
          final m = messages[i];
          final bool isMe = m['senderId'] == widget.myId;
          final bool isDel = m['isDeletedForEveryone'] ?? false;
          final bool isStar = m['starTag'] != null;
          final bool isPinned = m['isPinned'] ?? false;
          final bool isSch = m['scheduledTime']!=null && DateTime.parse(m['scheduledTime']).isAfter(DateTime.now());
          bool isFlashing = m['id'] == _flashingId;

          return GestureDetector(
            onLongPressStart: (d) => showMessageMenu(d.globalPosition, m, isMe),
            child: Align(alignment: isMe ? Alignment.centerRight : Alignment.centerLeft, child: AnimatedContainer(
              duration: const Duration(milliseconds: 500),
              constraints: BoxConstraints(maxWidth: MediaQuery.of(context).size.width*0.75),
              margin: const EdgeInsets.symmetric(vertical:5, horizontal:10),
              padding: const EdgeInsets.all(10),
              decoration: BoxDecoration(color: isFlashing ? Colors.yellow : (isMe ? const Color(0xFFBBDEFB) : Colors.white), borderRadius: BorderRadius.circular(10), boxShadow:[BoxShadow(color:Colors.grey.withOpacity(0.3), blurRadius:1)], border: isPinned ? Border.all(color: Colors.orange, width: 2) : null),
              child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [
                if(!isMe && widget.isGroup) Padding(padding: const EdgeInsets.only(bottom:5), child: Row(children: [buildProfileImage(m['senderIcon'], false, 14), const SizedBox(width:8), Text(m['senderName'], style:const TextStyle(fontSize:13, fontWeight:FontWeight.bold, color:Colors.deepPurple))])),
                if(isPinned) const Row(mainAxisSize: MainAxisSize.min, children: [Icon(Icons.push_pin, size:12, color:Colors.orange), SizedBox(width:4), Text("Sabitlendi", style:TextStyle(fontSize:10, fontWeight:FontWeight.bold, color:Colors.orange))]),
                if(isStar) Row(mainAxisSize: MainAxisSize.min, children: [const Icon(Icons.star, size:12, color:Colors.orange), const SizedBox(width:4), Text(m['starTag']!, style:const TextStyle(fontSize:10, fontWeight:FontWeight.bold, color:Colors.orange))]),
                Align(alignment: Alignment.centerRight, child: Text(decrypt(m['encryptedContent'], isDel), style: TextStyle(fontSize: 16, fontStyle: isDel?FontStyle.italic:FontStyle.normal, color: isDel?Colors.grey:Colors.black))),
                const SizedBox(height:4),
                Row(mainAxisAlignment: MainAxisAlignment.end, children: [
                  if(isSch) const Icon(Icons.access_time, size:12, color:Colors.grey),
                  Text(fmtTime(m['scheduledTime']??m['createdAt']), style: TextStyle(fontSize:11, color:Colors.grey[600])),
                  if(isMe && !isDel && !isSch && !widget.isGroup) ...[const SizedBox(width:5), buildTick(m['isDelivered'], m['isRead'])]
                ])
              ]),
            )),
          );
        })),
        if(replyingTo != null) Container(padding: const EdgeInsets.all(8), color: Colors.grey[200], child: Row(children: [const Icon(Icons.reply, color:Colors.grey), const SizedBox(width:10), Expanded(child: Text("Cevap veriliyor: ${replyingTo!.length>20?replyingTo!.substring(0,20)+'...':replyingTo}", maxLines:1, overflow:TextOverflow.ellipsis)), IconButton(icon: const Icon(Icons.close), onPressed: (){ setState(() { replyingTo=null; }); })])),
        Container(padding: const EdgeInsets.all(8), child: Row(children: [Expanded(child: Container(decoration: BoxDecoration(color:Colors.white, borderRadius:BorderRadius.circular(25)), child: TextField(controller: _msgCtrl, onSubmitted: (v)=>sendMessage(), decoration: const InputDecoration(hintText: "Mesaj yaz...", border: InputBorder.none, contentPadding: EdgeInsets.symmetric(horizontal:20, vertical:10))))), const SizedBox(width:5), GestureDetector(onLongPress: showScheduleMenu, child: CircleAvatar(backgroundColor: const Color(0xFF1565C0), radius:24, child: IconButton(icon: const Icon(Icons.send, color:Colors.white, size:20), onPressed: sendMessage)))
        ]))
      ]),
    );
  }
}